2024-03-06 00:31:30,835 ERROR: Exception on /add-comment [POST] [in /data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/Toolmux-Web-Jquery/app/community/views.py", line 22, in addComment
    comment = Comment(content = request.form['comment'], author = current_user._get_current_object())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/sqlalchemy/orm/state.py", line 566, in _initialize_instance
    with util.safe_reraise():
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/sqlalchemy/orm/state.py", line 564, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 2142, in _declarative_constructor
    raise TypeError(
TypeError: 'author' is an invalid keyword argument for Comment
2024-03-06 00:34:00,293 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-06 00:34:11,111 ERROR: Exception on /get-comments [GET] [in /data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/Toolmux-Web-Jquery/app/community/views.py", line 17, in getComments
    return jsonify({'comments': render_template('community/get_comments.html', comments = comments.items, next_url = next_url, prev_url = prev_url)})
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/data/data/com.termux/files/home/Toolmux-Web-Jquery/app/templates/community/get_comments.html", line 10, in top-level template code
    {% if comment.author.is_administrator() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'app.models.Comment object' has no attribute 'author'
2024-03-06 00:34:15,805 ERROR: Exception on /get-comments [GET] [in /data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/Toolmux-Web-Jquery/app/community/views.py", line 17, in getComments
    return jsonify({'comments': render_template('community/get_comments.html', comments = comments.items, next_url = next_url, prev_url = prev_url)})
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/data/data/com.termux/files/home/Toolmux-Web-Jquery/app/templates/community/get_comments.html", line 10, in top-level template code
    {% if comment.author.is_administrator() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/toolmux-web-venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'app.models.Comment object' has no attribute 'author'
2024-03-06 00:35:29,950 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-06 00:38:51,932 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-06 00:41:43,531 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-06 00:46:48,185 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-06 00:48:07,944 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-06 00:48:44,968 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-06 00:49:41,333 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-06 00:51:48,551 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-06 00:53:11,784 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-06 00:53:50,890 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-06 00:55:29,730 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
2024-03-06 00:59:04,521 INFO: Toolmux startup [in /data/data/com.termux/files/home/Toolmux-Web-Jquery/app/__init__.py:86]
